version: '3'
services:
  csharp_app:
    container_name: csharp_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Database=rental_db;Username=rental_username;Password=rental_password"
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=rental_username
      - POSTGRES_PASSWORD=rental_password
      - POSTGRES_DB=rental_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
